modules/MubAdmin/modules/hotels/models/Restaurant.php
<?php

namespace app\modules\MubAdmin\modules\hotels\models;

use Yii;
use app\models\MubUser;
use app\models\State;

/**
 * This is the model class for table "restaurant".
 *
 * @property integer $id
 * @property integer $mub_user_id
 * @property string $locality_name
 * @property string $lat
 * @property string $long
 * @property string $city_name
 * @property integer $state_id
 * @property string $restaurant_name
 * @property string $restaurant_slug
 * @property string $restaurant_type
 * @property string $sa_a
 * @property string $sa_b
 * @property string $status
 * @property string $description
 * @property integer $pincode
 * @property string $created_at
 * @property string $updated_at
 * @property string $del_status
 *
 * @property Menu[] $menus
 * @property MubUser $mubUser
 * @property State $state
 * @property RestaurantAmenities[] $restaurantAmenities
 * @property RestaurantImages[] $restaurantImages
 */
class Restaurant extends \app\components\Model
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'restaurant';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['mub_user_id', 'state_id', 'pincode'], 'integer'],
            [['restaurant_type', 'status', 'description', 'del_status'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['locality_name', 'lat', 'long', 'city_name', 'restaurant_name', 'restaurant_slug', 'sa_a', 'sa_b'], 'string', 'max' => 255],
            [['mub_user_id'], 'exist', 'skipOnError' => true, 'targetClass' => MubUser::className(), 'targetAttribute' => ['mub_user_id' => 'id']],
            [['state_id'], 'exist', 'skipOnError' => true, 'targetClass' => State::className(), 'targetAttribute' => ['state_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mub_user_id' => 'Mub User ID',
            'locality_name' => 'Locality Name',
            'lat' => 'Lat',
            'long' => 'Long',
            'city_name' => 'City Name',
            'state_id' => 'State ID',
            'restaurant_name' => 'Restaurant Name',
            'restaurant_slug' => 'Restaurant Slug',
            'restaurant_type' => 'Restaurant Type',
            'sa_a' => 'Sa A',
            'sa_b' => 'Sa B',
            'status' => 'Status',
            'description' => 'Description',
            'pincode' => 'Pincode',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'del_status' => 'Del Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenus()
    {
        return $this->hasMany(Menu::className(), ['restaurant_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMubUser()
    {
        return $this->hasOne(MubUser::className(), ['id' => 'mub_user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getState()
    {
        return $this->hasOne(State::className(), ['id' => 'state_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRestaurantServices()
    {
        return $this->hasMany(RestaurantServices::className(), ['restaurant_id' => 'id']);
    }
    

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRestaurantImages()
    {
        return $this->hasMany(RestaurantImages::className(), ['restaurant_id' => 'id']);
    }
}

modules/MubAdmin/modules/hotels/controllers/RestaurantController.php
<?php

namespace app\modules\MubAdmin\modules\hotels\controllers;

use app\components\MubController;
use app\modules\MubAdmin\modules\hotels\models\RestaurantSearch;
use app\modules\MubAdmin\modules\hotels\models\Restaurant;
use app\modules\MubAdmin\modules\hotels\models\RestaurantProcess;
use app\modules\MubAdmin\modules\hotels\models\RestaurantImages;
use yii\web\UploadedFile;

use yii\helpers\FileHelper;
use yii\helpers\Json;

class RestaurantController extends MubController
{
   public function getPrimaryModel()
   {
		  return new Restaurant();
   }

   public function getProcessModel()
   {
      return new RestaurantProcess();
   }

   public function getSearchModel()
   {
      return new RestaurantSearch();
   }

    public function updateUserRecord($postData)
    {
      $userModel = new \app\models\User();
      $mubUserModel = new \app\models\MubUser();
      $mubUser = $mubUserModel::findOne($postData['MubUser']['id']);
      $mubUserContact = $mubUser->mubUserContacts;
      $user = $userModel::findOne($mubUser->user_id);
      $user->first_name = $postData['MubUser']['first_name'];
      $user->last_name = $postData['MubUser']['last_name'];
      $user->setPassword($postData['MubUser']['password']);
      $user->generateAuthKey();
      $user->generatePasswordResetToken();
      return ($user->save(false)) ? true : p($user->getErrors());
    }
  
    public function actionProfile()
    {   
        if (\Yii::$app->user->isGuest) {
            $this->redirect('/mub-admin');
        }
        else 
        {
            if(\Yii::$app->request->post())
            {
                $postData = \Yii::$app->request->post();
                $userModel = new \app\models\User();
                $mubUserModel = new \app\models\MubUser();
                $mubUser = $mubUserModel::findOne($postData['MubUser']['id']);
                $user = $userModel::findOne($mubUser->user_id);
                $mubUserContact = $mubUser->mubUserContacts;
            
                if($mubUser->load($postData) && $mubUserContact->load($postData))
                {
                    if($mubUser->save(false) && $mubUserContact->save(false))
                    {
                        $success = $this->updateUserRecord($postData);
                        if($success)
                        {
                            return $this->goBack('/mub-admin/hotels/restaurant/profile');
                        }
                    }
                }
                p([$mubUser->getErrors(),$mubUserContact->getErrors()]);
            }
            return $this->render('profile');
        }
    }

   public function actionRestaurantImage($state)
   {
    if (\Yii::$app->request->isAjax) {
      $model = new RestaurantImages();

      $imageFile = UploadedFile::getInstance($model, 'url');

      $directory = \Yii::getAlias('@app/images/properties') . DIRECTORY_SEPARATOR . \Yii::$app->request->getQueryParam('state') . DIRECTORY_SEPARATOR;
      if (!is_dir($directory)) {
          FileHelper::createDirectory($directory);
      }
      if ($imageFile) {
          $uid = uniqid(time(), true);
          $fileName = $uid . '.' . $imageFile->extension;
          $filePath = $directory . $fileName;
          if ($imageFile->saveAs($filePath)) {
              $path = '/images/properties/'.\Yii::$app->request->getQueryParam('state') . DIRECTORY_SEPARATOR.$fileName;
              $model->mub_user_id = \app\models\User::getMubUserId();
              $model->restaurant_id = NULL;
              $model->title = $uid . '.' . $imageFile->extension;
              $model->description = $imageFile->name.'.'.$imageFile->extension;
              $model->url = $path;
              $model->thumbnail_url = $path;
              $model->full_path = $path;
              if(!$model->save())
              {
                p($model->getErrors());
              }
              
              $successPath = '/images/done.png';
              return Json::encode([
                  'files' => [
                      [
                          'name' => $fileName,
                          'size' => $imageFile->size,
                          'url' => $successPath,
                          'thumbnailUrl' => $successPath,
                          'deleteUrl' => 'image-delete?name=' . $fileName,
                          'deleteType' => 'POST',
                      ],
                  ],
              ]);
          }
      }
      return '';
    }else
    {
      return 'go away';
    }
  }

  public function actionImageDelete($name)
  {
     if (\Yii::$app->request->isAjax) {
      $stateId = \Yii::$app->request->getQueryParam('state');
      $directory = \Yii::getAlias('@app/images/properties') . DIRECTORY_SEPARATOR . $stateId . DIRECTORY_SEPARATOR;
      if (is_file($directory.$name)) 
      {
          if(unlink($directory . $name))
          {
            $restaurantImages = new \app\modules\MubAdmin\modules\hotels\models\RestaurantImages();
            $success = $restaurantImages::deleteAll(['title' => $name]);
            if($success)
            {
              return 'Image Deleted Successfully'; 
            }
          }else
          {
            return 'There was a problem deleting the Image';
          }
      }
      else
      {
        $restaurantImages = new \app\modules\MubAdmin\modules\hotels\models\RestaurantImages();
        $success = $restaurantImages::deleteAll(['title' => $name]);
        if($success)
        {
          return 'Image Deleted from Records'; 
        }
      }
      
  }else
  {
    return 'Go Awayyyy!';
  }
}
}

modules/MubAdmin/modules/hotels/views/restaurant/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;
use dosamigos\fileupload\FileUploadUI;
use app\helpers\ImageUploader;
use dosamigos\tinymce\TinyMce;

$stateId = \Yii::$app->request->getQueryParam('state');
        if($stateId == '')
        {
            $stateId = \Yii::$app->request->getBodyParam('state');
        }

$restaurantImages = new app\modules\MubAdmin\modules\hotels\models\RestaurantImages();
$images = $restaurantImages::find()->where(['restaurant_id' => $restaurant->id,'del_status' => '0'])->all();

/* @var $this yii\web\View */
/* @var $restaurant app\modules\MubAdmin\modules\hotels\restaurants\restaurant */
/* @var $form yii\widgets\ActiveForm */

$state = new \app\models\State();
$stateName = \app\helpers\StringHelper::generateSlug($state::findOne($stateId)->state_name);

?>

<style>
    .toggle
    {
        display:none;
    }
</style>
<?php if(!empty($allServices)){?>

<div class="property-form">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
        <br/><h4>Upload Imgaes</h4><br/>
        <?= FileUploadUI::widget([
        'model' => $restaurantImages,
        'attribute' => 'url',
        'url' => ['restaurant/restaurant-image', 'state' => \Yii::$app->request->getQueryParam('state'),'restaurant' => $restaurant->id],
        'gallery' => false,
        'fieldOptions' => [
            'accept' => 'image/*'
        ],
        'clientOptions' => [
            'maxFileSize' => 5000000
        ],
        'clientEvents' => [
            'fileuploaddone' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
            'fileuploadfail' => 'function(e, data) {
                                    console.log(e);
                                    console.log(data);
                                }',
            ],
        ]); ?>
        </div>
    </div>
    <?php $form = ActiveForm::begin(); ?>

    <?php if(!empty($images)){?>
 <?php  foreach($images as $key=>$image){?>
    <div id="uploaded<?php echo $key;?>" style="display: inline; margin-right: 10px;">
    <?php echo Html::img(ImageUploader::resizeRender($image->url, '100', '100'),['height'=>100,'width'=>100]);
    echo Html::a(
        Yii::t('app', 'x'),
        '#',
        ["class" => "btn btn-danger del-image","id" => $image->title]);
    ?>
     </div>
     <?php }}?>
     <div class="row">
    
    <div class="col-md-5 col-sm-12 col-xs-12 col-md-offset-1">

    <?= $form->field($restaurant, 'restaurant_name')->textInput(['maxlength' => true]) ?>
    </div>
    <div class="col-md-5 col-sm-12 col-xs-12">
    <?= $form->field($restaurant, 'restaurant_type')->dropDownList([ 'veg' => 'Veg', 'non-veg' => 'Non-Veg', 'both' => 'Both'], ['prompt' => 'Select restaurant Type']) ?>
    </div>
    <div class="col-md-5 col-sm-12 col-xs-12 col-md-offset-1">
    </div>
    <?= $form->field($restaurant,'lat')->hiddenInput(['id' => 'lat'])->label(false);?>
    
    <?= $form->field($restaurant,'long')->hiddenInput(['id' => 'long'])->label(false);?>
    
    <?= $form->field($restaurant,'city_name')->hiddenInput(['id' => 'city_name'])->label(false);?>
    
    <?= $form->field($restaurant,'pincode')->hiddenInput(['id' => 'pincode'])->label(false);?>
    
    <?= $form->field($restaurant,'locality_name')->hiddenInput(['id' => 'locality'])->label(false);?>
   
    <div class="col-md-10 col-sm-12 col-xs-12 col-md-offset-1">
    <?= $form->field($restaurant, 'sa_a')->textInput(['maxlength' => true,'placeholder' => 'Like plot Number/Khasra number'])->label('Street address Line1');?>
    </div>
    <div class="col-md-10 col-sm-12 col-xs-12 col-md-offset-1 ">
    <?= $form->field($restaurant, 'sa_b')->textInput(['maxlength' => true,'placeholder'=> 'Sector / Locality name'])->label('Street address Line2'); ?>
    </div>
    <div class="col-md-10 col-sm-12 col-xs-12 col-md-offset-1">

    <?= $form->field($restaurant, 'description')->widget(TinyMce::className(), [
    'options' => ['rows' => 6],
    'language' => 'en_GB',
    'clientOptions' => [
        'plugins' => [
            "advlist autolink lists link charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste"
        ],
        'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
        ]
    ]);?>
    </div>
    <div class="col-md-10 col-sm-12 col-xs-12 col-md-offset-1 ">
    <?= $form->field($restaurant, 'status')->dropDownList([ 'active' => 'Active', 'inactive' => 'Inactive', ], ['prompt' => 'Select restaurant Status']);?>
    </div>
    </div>
<input type="hidden" id="current-state-name" value="<?=$stateName;?>">
    <div class="col-md-10 col-sm-12 col-xs-12 col-md-offset-1">
    <?php echo $form->field($restaurantServices, 'service_id')->checkboxList($allServices)->label('Services'); ?>
    </div>
    </div>
    <div class="form-group" style="text-align: center;" >
        <?= Html::submitButton($restaurant->isNewRecord ? 'Create' : 'Update', ['class' => $restaurant->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?php if(!$restaurant->isNewRecord){?>
        <?= Html::a('Cancel', ['/mub-admin/hotels/restaurant','state' => $stateId], ['class' => 'btn btn-warning cancel'])?>
         <?php }?><br/><br/>
    </div>
</div>

<input type="hidden" id="current-state-id" value="<?=$stateId;?>">
    <?php ActiveForm::end(); ?>
    <?php }else{?><br/><br/><br/>
<h3>Please Create Some Services first to associate your Products with</h3>
<br /><br />
<h4><--- You can click on the Services option from Left Menu to create new Services</h4>

<?php }?>

</div>

modules/MubAdmin/modules/hotels/views/restaurant/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $property app\modules\MubAdmin\modules\hotels\propertys\PropertySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="property-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($restaurant, 'id') ?>

    <?= $form->field($restaurant, 'mub_user_id') ?>

    <?= $form->field($restaurant, 'rooms_count') ?>

    <?= $form->field($restaurant, 'lat') ?>

    <?= $form->field($restaurant, 'long') ?>

    <?php // echo $form->field($restaurant, 'city_name') ?>

    <?php // echo $form->field($restaurant, 'state_id') ?>

    <?php // echo $form->field($restaurant, 'restaurant_name') ?>

    <?php // echo $form->field($restaurant, 'restaurant_slug') ?>

    <?php // echo $form->field($restaurant, 'restaurant_type') ?>

    <?php // echo $form->field($restaurant, 'restaurant_area') ?>

    <?php // echo $form->field($restaurant, 'sa_a') ?>

    <?php // echo $form->field($restaurant, 'sa_b') ?>

    <?php // echo $form->field($restaurant, 'description') ?>

    <?php // echo $form->field($restaurant, 'pincode') ?>

    <?php // echo $form->field($restaurant, 'created_at') ?>

    <?php // echo $form->field($restaurant, 'updated_at') ?>

    <?php // echo $form->field($restaurant, 'del_status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/MubAdmin/modules/hotels/views/restaurant/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $restaurant app\modules\MubAdmin\modules\hotels\restaurants\restaurant */

$this->title = 'Create Restaurant';
$this->params['breadcrumbs'][] = ['label' => 'Restaurant', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="restaurant-create">
<div class="col-md-10 col-md-offset-1">
    <h1><?= Html::encode($this->title) ?></h1>
</div>
    <?= $this->render('_form', [
        'restaurant' => $restaurant,
        'allServices' => $allServices,
        'restaurantServices' => $restaurantServices,
    ]) ?>

</div>

modules/MubAdmin/modules/hotels/views/restaurant/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Breadcrumbs;

$this->params['breadcrumbs'][] = ['label' => 'Restaurant', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

   echo Breadcrumbs::widget([
      'homeLink' => [ 
                      'label' => Yii::t('yii', 'Dashboard'),
                      'url' => Yii::$app->homeUrl,
                 ],
      'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
   ]); 
$stateId = \Yii::$app->request->getQueryParam('state');
if($stateId == '')
{
    $stateId = \Yii::$app->request->getBodyParam('state');
}

$state = new app\models\State();
$currentState = $state::findOne($stateId);
$this->title = 'Restaurants of '.$currentState->state_name;
$state = \Yii::$app->getRequest()->getQueryParam('state');
?>
<div class="property-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Restaurant', ['create','state' => $state], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'layout' => "{summary}\n{items}\n<div align='center'>{pager}</div>",
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'restaurant_name',
            'restaurant_type',
            'sa_a',
            'sa_b',
            'city_name',
            
             [
                'attribute' => 'status',
                'format' => 'raw',
                'value' => function ($model) {
                    $userRole = \Yii::$app->controller->getUserRole();
                    if($userRole == 'admin'){
                        $modelName = str_replace('\\','\\\\',get_class($model));
                    $attrib = 'status'; 
                    $valActive = 'active';
                    $id = $model->id;
                    $valInactive = 'inactive';
                    return ($model->status == 'inactive') ? '<button onClick="alert(setModelAttribute('.'\''.$modelName.'\''.','.'\''.$attrib.'\''.','.'\''.$valActive.'\''.','.'\''.$id.'\''.'))">Activate</button>' : '<button onClick="alert(setModelAttribute('.'\''.$modelName.'\''.','.'\''.$attrib.'\''.','.'\''.$valInactive.'\''.','.'\''.$id.'\''.'))">Deactivate</button>';    
                    }
                    else
                    {
                        return $model->status;
                    }
                    
                },
            ],
            // 'city_name',
            // 'state_id',
            // 'restaurant_slug',
            // 'description:ntext',
            // 'pincode',
            // 'created_at',
            // 'updated_at',
            // 'del_status',

            ['header' => 'Actions','class' => 'app\components\MubActionColumn'],
        ],
    ]); ?>
</div>

modules/MubAdmin/modules/hotels/views/restaurant/profile.php
<?php 
namespace app\modules\MubAdmin\modules\hotels\controllers;

use yii\bootstrap\ActiveForm;
$mubUserId = \app\models\User::getMubUserId();
$mubUserModel = new \app\models\MubUser();
$currentUser = $mubUserModel::findOne($mubUserId);
$userDetails = $currentUser;
$contactDetails = $currentUser->mubUserContacts;
?>
<style type="text/css">.has-success .form-control{
  border-radius: 20px!important;
}</style>
<div class="container">
     <div class="col-md-12 text-center" style="margin:1em;">
      <h3> Profile</h3>
      <h5 style="color: #6B7C8E;"><b style="color: red;">*</b> You can  change Password  from this page</h5>
      </div
      <div class="agent-grids">
      <div class="col-md-12 agent-grid">
         <div class="col-md-1 col-md-offset-2"> 
           
         </div>
         <div class="col-md-6 col-md-offset-1 agent-right" style="width: 50%; margin-top: 2em;">
            <?php $form = ActiveForm::begin(['layout' => 'horizontal','options' => ['method' => 'POST'],'action' => ['/mub-admin/hotels/property/profile']]); ?>
            <?= $form->field($currentUser, 'first_name')->textInput(['autofocus' => true,'class' => 'form-control']);?>
           <?= $form->field($currentUser, 'last_name')->textInput(['class' => 'form-control']);?>
            <?= $form->field($currentUser, 'username')->textInput(['class' => 'form-control','readonly' => true]);?>
            <?= $form->field($currentUser, 'password')->passwordInput(['class' => 'form-control']);?>
            <?= $form->field($contactDetails, 'mobile')->textInput(['class' => 'form-control','maxlength' => 10]);?>
             <?= $form->field($contactDetails, 'email')->textInput(['class' => 'form-control','readonly' => true]);?>
             <?= $form->field($currentUser,'id')->hiddenInput()->label(false);?>
           <center><input type="submit" value="Update" style="margin-bottom: 2em!important;"></center>
           <?php ActiveForm::end(); ?>
         </div>
         <div class="clearfix"></div>
      </div>
</div>

modules/MubAdmin/modules/hotels/views/restaurant/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $property app\modules\MubAdmin\modules\hotels\propertys\Property */

$this->title = 'Update restaurant: ' . $restaurant->restaurant_name;
$this->params['breadcrumbs'][] = ['label' => 'Restaurants', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $restaurant->restaurant_name, 'url' => ['view', 'id' => $restaurant->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="restaurant-update">
<div class="col-md-10 col-md-offset-1">

    <h1><?= Html::encode($this->title) ?></h1>
</div>
    <?= $this->render('_form', [
        'restaurant' => $restaurant,
        'allServices' => $allServices,
        'restaurantServices' => $restaurantServices,
    ]) ?>

</div>

modules/MubAdmin/modules/hotels/views/restaurant/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use dosamigos\fileupload\FileUploadUI;
use app\helpers\ImageUploader;
/* @var $this yii\web\View */
/* @var $property app\modules\MubAdmin\modules\hotels\propertys\Property */

$this->title = $restaurant->restaurant_name;
$this->params['breadcrumbs'][] = ['label' => 'Restaurants', 'url' => ['index']];
$stateId = \Yii::$app->request->getQueryParam('state');
if($stateId == '')
{
    $stateId = \Yii::$app->request->getBodyParam('state');
}
$this->params['breadcrumbs'][] = $this->title;

$restaurantImages = new app\modules\MubAdmin\modules\hotels\models\RestaurantImages();
$images = $restaurantImages::find()->where(['restaurant_id' => $restaurant->id,'del_status' => '0'])->all();

?>
<style>
    .toggle
    {
        display:none;
    }
</style>
<div class="property-view">
<?= Html::a('Add/View Menu', ['/mub-admin/hotels/menu', 'restaurant' => $restaurant->id,'state' => $stateId], ['class' => 'btn btn-info btn-lg pull-right'])?>
<div class="col-md-10 col-md-offset-1">
    <h1><?= Html::encode($this->title) ?></h1>
</div>
<div class="row">
<div class="col-md-10 col-md-offset-1">
    <?= FileUploadUI::widget([
    'model' => $restaurantImages,
    'attribute' => 'url',
    'url' => ['restaurant/restaurant-image', 'state' => \Yii::$app->request->getQueryParam('state'),'restaurant' => $restaurant->id],
    'gallery' => false,
    'fieldOptions' => [
        'accept' => 'image/*'
    ],
    'clientOptions' => [
        'maxFileSize' => 5000000
    ],
    'clientEvents' => [
        'fileuploaddone' => 'function(e, data) {
                                console.log(e);
                                console.log(data);
                            }',
        'fileuploadfail' => 'function(e, data) {
                                console.log(e);
                                console.log(data);
                            }',
        ],
    ]); ?>
</div>
</div>
<div class="row">
<div class="col-md-10 col-md-offset-1">
    <?php if(!empty($images)){?>
 <?php  foreach($images as $key=>$image){
                    ?>

                    <div id="uploaded<?php echo $key;?>" style="display: inline; margin-right: 10px;">
                    <?php echo Html::img(ImageUploader::resizeRender($image->url, '100', '100'),['height'=>100,'width'=>100]);
                    echo Html::a(
                        Yii::t('app', 'x'), 
                        '#',
                        ["class" => "btn btn-danger realign","onClick" => "deleteFile('".$key."')"]);
                    ?>
                     </div>
                     <?php }}?>
 </div>
</div>
 <div class="row">
    <div class="col-md-5 col-md-offset-1">
<div class="col-md-12" style="margin-top: 2em;">
    <?= DetailView::widget([
        'model' => $restaurant,
        'attributes' => [
            'restaurant_name',
            'restaurant_type',
            'description:ntext',
            'sa_a',
            'sa_b',
           
        ],
    ]) ?>
    </div>
   </div>
</div>
     <div class="row">
        <div class="col-md-5 col-md-offset-1">
     <div class="col-md-12">
        <?= Html::a('Update', ['update', 'id' => $restaurant->id,'state' => $stateId], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $restaurant->id,'state' => $stateId], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>

        <?= Html::a('All Restaurant', ['index','state' => $stateId], [
            'class' => 'btn btn-primary cancel',
        ]) ?>
     </div>
      </div>
   </div>

</div>